---
# tasks for linux hosts

- name: ensure icinga2 repository is installed
  yum:
    name: "{{ icinga2_repo_icinga_url }}"
  when: icinga2_node_repo_icinga_install

- name: ensure epel-release is installed
  yum:
    name: epel-release
    state: present
  when: icinga2_node_repo_epel_install

- name: ensure icinga2 is installed
  yum:
    name: icinga2
    disable_gpg_check: yes
    state: present

- name: ensure icinga2 service is enabled
  service:
    name: icinga2
    enabled: true

- name: ensure icinga2 service restarts on failure if set
  lineinfile:
    path: /usr/lib/systemd/system/icinga2.service
    line: Restart=on-failure
    insertafter: .*TimeoutStartSec.*
  when: icinga2_restart_on_failure

- name: ensure icinga2 service doesn't restart on failure if set
  lineinfile:
    path: /usr/lib/systemd/system/icinga2.service
    line: Restart=on-failure
    state: absent
  when: not icinga2_restart_on_failure

- name: ensure nagios-plugins are installed
  yum:
    name: "{{ icinga2_node_nagios_plugins }}"
    state: present

- name: ensure rpcbind.socket is disabled
  systemd:
    name: '{{ item }}'
    enabled: false
    state: stopped
  with_items:
    - rpcbind.socket
    - rpcbind.service
  when: false # error -> rpcbind service / socket does not exist on new systems

- name: configuration
  include_tasks: linux_config.yml
  when: not icinga2_install_only
