---
# tasks for windows hosts

- name: ensure icinga2 is installed (using chocolatey)
  win_chocolatey:
    name: icinga2
    state: latest  # noqa 403
    source:  "{{ icinga2_chocolatey_source | default(omit) }}"
  register: icinga2_win_install

- name: ensure service user is configured
  win_service:
    name: icinga2
    state: present
    username: "{{ icinga2_node_service_username }}"
    password: "{{ icinga2_node_service_password }}"
  when: icinga2_node_service_username is defined
  notify: windows node restart icinga2 service

- name: configuration
  include_tasks: windows_config.yml
  when: not icinga2_install_only
